### ISSUE TITLE
Limit API param is not used as should

### ISSUE THREAD

**Issue by pedrovgs** [Karumi/MarvelApiClient#5]
@flipper83 has noticed that the ``limit`` param used in the API is associated to the number of items you want to retrieve and not from the last item you want to retrieve. We should change this in the client side api to use ``size`` or ``count`` as named param instead of ``limit`` and also change a precondition we had related to this param.

**Comment by davideme** [comment]
Offset and limit are the usual name used in database. I'm fine with that.
But if you want a name that give more semantic to you I understand
